### PR TITLE
feat(cmd): add tag system

### PR DESCRIPTION
**Pull request by ToasterSticks**
• Added tag command, to replace existing commands with static responses (left out cave monkey becuz stupid embed)

### CODE REVIEW

**Review by ToasterSticks — COMMENTED** [review]
LGTM!!!

**Comment by hemisemidemipresent** [comment]
vrej

**Comment by hemisemidemipresent** [comment]
~~smh star the repo~~

**Comment by ToasterSticks** [comment]
Forgot to delete cave-monkey.js

**Pull request merged**
