### PR TITLE
Tidy exports

### PR DESCRIPTION
**Pull request by Topper64**
Rationalising a few of the imports/exports.

See commit messages for details, but the key change is defining things first, then separately exporting them. Plus some miscellaneous fixing/tidying, but I did try to keep this branch about the exports only.

I only really focussed on the helpers, because I can see that commands/parsing are gradually being reworked and didn't want to interfere with that too much. It would be nice if the same principle could be applied in that process, but I don't mind combing through again at some later point.

What I mean is instead of putting all the functions in the exported object
```
module.exports = {
    IMPORTANT_THING: "foo",
    doThing() {},
    async doOtherThing() {},
}
```
we define things then export them
```
const IMPORTANT_THING = "foo"

function doThing() {}
async function doOtherThing() {}

module.exports = {
    IMPORTANT_THING,
    doThing,
    doOtherThing,
}
```

It *is* mildly annoying to need to name each function/constant twice, but the advantages are:
- functions are defined with an actual function keyword now, which is more clear
- saved one level of indentation from basically everything
- neater references to other things in the same file, because they're called eg `doThing` instead of `module.exports.doThing`
- greater separation of concerns - there is now a concept of "private" (to a module) and "public" (available for other modules)

I don't know what amount of testing is expected, or indeed what amount of functionality is expected. It does run at least, but a simple `q!dart` command breaks, and the error is clearly nothing to do with what I've changed. So I'll just put this here as it is.

### CODE REVIEW

**Comment by Topper64** [comment]
OK as I thought, I fixed the style issue and the other one fixed itself. Because all it's doing it trying to add a comment to this pull request, but doesn't have the permissions to do so. But it only does it for users it's *never* seen before, so didn't bother the second time.

**Review by rmlgaming — COMMENTED** [review]
I am totally on board with these changes. I am still learning nodejs best practices.

**Comment by rmlgaming** [comment]
It would be hard to ensure that everything works after such a large refactor. Test some basic commands `q!info`, index commands `q!3tcabr wlp ed`, cash-commands `q!income R40 20 abr`, tower commands `q!dart 300`, static commands `q!vtsg`.

**Comment by hemisemidemipresent** [comment]
Apart from the currently broken statcord bot posting, everything else seems to be working,

**Comment by Topper64** [comment]
Is statcord not working something I should be concerned about? It didn't seem necessary to set it up - hence the change to not break if I don't. Nothing else about it should have changed though. Note that you do still need to set the `botposting` config value for it to do anything.

**Comment by hemisemidemipresent** [comment]
currently, the main branch of statcord posting isnt working, due to a currently unknown erro:
```
(node:52) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
     at Statcord.post (/app/node_modules/statcord.js/src/Statcord.js:148:34)
     at Statcord.autopost (/app/node_modules/statcord.js/src/Statcord.js:234:31)
     at botStats (/app/server.js:141:14)
     at main (/app/server.js:12:5)
     at Object.<anonymous> (/app/server.js:148:1)
```
However, this branch had a new error pop up, which I think is due to the reformatting:
```
C:\...\helpers\botinfo.js:20
    statcord.on('autopost-start', () => {
             ^

TypeError: statcord.on is not a function
    at Object.statcord (C:\...\helpers\botinfo.js:20:14)
    at botStats (C:\...\server.js:138:19)
    at main (C:\...\server.js:12:5)
    at Object.<anonymous> (C:\...\server.js:147:1)
```

**Comment by Topper64** [comment]
Ahh, I understand what's going on there. Should be fixed.

Also I saw that the branch conflicted with recent changes to master, so resolved that.

**Comment by rmlgaming** [comment]
I won't be pushing changes until this is merged so hopefully no more rebasing for you

**Comment by hemisemidemipresent** [comment]
alright it should be ready to merge soon

**Pull request merged**
