### PR TITLE
LCD Command

### PR DESCRIPTION
**Pull request by alexmi3**
New main index challenge. I think this should work, given i copied the lcc command, but change every instance of 'lcc' to 'lcd'.

### CODE REVIEW

**Comment by rmlgaming** [comment]
@alexmi3 I think it'd be good for now and for the future to have a local working copy of the bot so you can be sure and test. Here are the steps: https://github.com/hemisemidemipresent/cyberquincy#basic-local-test-guide

**Comment by rmlgaming** [comment]
You'll need to get the google spreadsheet credentials for `/lcd`.

**Comment by alexmi3** [comment]
what is that?

**Comment by rmlgaming** [comment]
@alexmi3 So basically the way I ensure that my commands work is that I have a "copy" of cyberquincy that I control and I have in a personal server with no one else in it. That copy runs off a local copy of your code - in your case `Alexmi3:master` (or whatever branch you have checked out) - and works just the same.

In order to get this set up, you'll need to follow steps 1 and 2 of the instructions I linked above.

**Comment by rmlgaming** [comment]
Either that or you could get hemi to test the command as cyber quincy [beta] in the server. But for future reference, that'll make development time really slow for you if you make a mistake on a future addition/change to the bot.

**Comment by hemisemidemipresent** [comment]
is this ready to merge or does this still need testing? @rmlgaming

**Comment by rmlgaming** [comment]
Needs testing. Also this is not in the v14 style..

**Comment by ToasterSticks** [comment]
Unable to get real

**Pull request closed without merging**
